application:
  subdomain: navidrome
  multi_instance: true
  upstreams:
    - location: /
      backend: http://navidrome:4533/
  public_path:
    - /
  health_check:
    test_url: http://navidrome:4533/ping

services:
  navidrome:
    # upstream: docker.1ms.run/deluan/navidrome:0.63.2
    image: docker.1ms.run/deluan/navidrome:0.63.2
    user: "root"
    environment:
      - ND_PORT=4533
      - ND_DATAFOLDER=/data
      - ND_MUSICFOLDER=/lzcapp/run/mnt/home/{{ .U.music_dir }}
      - ND_DEEZER_LANGUAGE={{ .U.deezer_language }}
    binds:
      - /lzcapp/var/data:/data
ext_config:
  enable_document_access: true
usage: |
  首次打开 Navidrome 时，请在其原生初始化页面创建管理员账号。音乐库读取安装向导中选择的目录，应用数据保存在微服实例的持久目录中。
